spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource
    
mybatis:
  type-aliases-package: com.itheima.domain